[package]
name = "dc_rest"
version = "10.0.0"
authors = ["CtrlX <gitctrlx@gmail.com>"]
description = "Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details."
license = "MIT"
edition = "2024"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.13", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
async-trait = "^0.1"
reqwest = { version = "^0.12", default-features = false, features = ["json", "multipart"] }
reqwest-middleware = { version = "^0.4", features = ["json", "multipart"], optional = true }

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]
middleware = ["reqwest-middleware"]